---
#- import_tasks: pass-24.yml
#- import_tasks: spooler.yml
#- import_tasks: max_password.yml
#- import_tasks: min_password.yml
#- import_tasks: password_complexity.yml
#- import_tasks: password_using_reversible_encryption.yml
#- import_tasks: Account_lockout_duration.yml
#- import_tasks: Account_lockout_threshold.yml
#- import_tasks: Allow_Administration_account_lockout_set_enabled.yml
#- import_tasks: Reset_account_lockout_counter_after_set_to_15min_more.yml
#- import_tasks: Ensure_Access_Credential_Manager_trusted_caller_set_to_No_One.yml
#- import_tasks: Ensure_Access_computer_from_network_is_set_administrators_and_authusers.yml
#- import_tasks: Ensure_Act_as_part_operating_system_set_to_No_One.yml
#- import_tasks: Ensure_Adjust_memory_quota_for_process_set_Administrators_LOCAL-SERVICE_NETWORK-SERVICE.yml
#- import_tasks: Ensure_Allow_log_on_locally_set_to_Administrators.yml
#- import_tasks: Ensure_Allow_log_on_through_Remote_Desktop_Services_set_to_Administrators_Remote-Desktop-Users.yml
#- import_tasks: Ensure_back_up_files_directories_is_set_to_Administrators.yml
#- import_tasks: Ensure_Change_the_system_time_is_set_to_Administrators_LOCAL_SERVICE.yml
#- import_tasks: Ensure_Change_the_time_zone_set_to_Administrators_LOCAL-SERVICE.yml
#- import_tasks: Ensure_Create_pagefile_is_set_to_Administrators.yml
#- import_tasks: Ensure_Create_a_token_object_is_set_to_No-One.yml
#- import_tasks: Ensure_Create_global_objects_is_set_to_Administrators_LOCAL_SERVICE_NETWORK-SERVICE_SERVICE.yml
#- import_tasks: Ensure_Create_permanent_shared_objects_is_set_to_No-One.yml
- import_tasks: Ensure_Create_symbolic_links_is_set_to_Administrators_NT-VIRTUAL_MACHINE-Virtual_Machines.yml
- import_tasks: Ensure_Debug_programs_is_set_to_Administrators.yml 
