---
#- import_tasks: pass-24.yml
#- import_tasks: spooler.yml
#- import_tasks: max_password.yml
#- import_tasks: min_password.yml
#- import_tasks: password_complexity.yml
#- import_tasks: password_using_reversible_encryption.yml
#- import_tasks: Account_lockout_duration.yml
#- import_tasks: Account_lockout_threshold.yml
#- import_tasks: Allow_Administration_account_lockout_set_enabled.yml
#- import_tasks: Reset_account_lockout_counter_after_set_to_15min_more.yml
#- import_tasks: Ensure_Access_Credential_Manager_trusted_caller_set_to_No_One.yml
#- import_tasks: Ensure_Access_computer_from_network_is_set_administrators_and_authusers.yml
#- import_tasks: Ensure_Act_as_part_operating_system_set_to_No_One.yml
#- import_tasks: Ensure_Adjust_memory_quota_for_process_set_Administrators_LOCAL-SERVICE_NETWORK-SERVICE.yml
#- import_tasks: Ensure_Allow_log_on_locally_set_to_Administrators.yml
#- import_tasks: Ensure_Allow_log_on_through_Remote_Desktop_Services_set_to_Administrators_Remote-Desktop-Users.yml
#- import_tasks: Ensure_back_up_files_directories_is_set_to_Administrators.yml
#- import_tasks: Ensure_Change_the_system_time_is_set_to_Administrators_LOCAL_SERVICE.yml
#- import_tasks: Ensure_Change_the_time_zone_set_to_Administrators_LOCAL-SERVICE.yml
#- import_tasks: Ensure_Create_pagefile_is_set_to_Administrators.yml
#- import_tasks: Ensure_Create_a_token_object_is_set_to_No-One.yml
#- import_tasks: Ensure_Create_global_objects_is_set_to_Administrators_LOCAL_SERVICE_NETWORK-SERVICE_SERVICE.yml
#- import_tasks: Ensure_Create_permanent_shared_objects_is_set_to_No-One.yml
#- import_tasks: Ensure_Create_symbolic_links_is_set_to_Administrators_NT-VIRTUAL_MACHINE-Virtual_Machines.yml
#- import_tasks: Ensure_Debug_programs_is_set_to_Administrators.yml
#- import_tasks: Ensure_Deny_access_to_computer_the_network_to_include_Guests_Local-account_member_of_Administrators_group.ym
#- import_tasks: Ensure_Deny_log_on_as_batch_job_to_include_Guests.yml
#- import_tasks: Ensure_Deny_log_on_as_service_to_include_Guests.yml
#- import_tasks: Ensure_Deny_log_on_locally_to_include_Guests.yml
#- import_tasks: Ensure_Deny_log_on_through_Remote_Desktop_Services_is_set_to_Guests_Local_account.yml
#- import_tasks: Ensure_Enable_computer_user_accounts_to_be_trusted_for_delegation_set_to_No-One.yml
#- import_tasks: Ensure_Force_shutdown_from_remote_system_set_to_Administrators.yml
#- import_tasks: Ensure_Generate_security_audits_is_set_to_LOCAL-SERVICE_NETWORK-SERVICE.yml
#- import_tasks: Ensure_Impersonate_client_after_authentication_set_to_Administrators_LOCAL-SERVICE_NETWORK-SERVICE_SERVICE_when_Web-Server_IIS_IUSRS.yml
#- import_tasks: Ensure_Increase_scheduling_priority_is_set_to_Administrators_Window-Manager_Window-Manager-Group.yml
#- import_tasks: Ensure_Load_and_unload_device_drivers_is_set_to_Administrators.yml
#- import_tasks: Ensure_Lock_pages_in_memory_is_set_to_No_One.yml
#- import_tasks: Ensure_Manage_auditing_and_security_log_is_set_to_Administrators.yml
#- import_tasks: Ensure_Modify_an_object_label_is_set_to_No-One.yml
#- import_tasks: Ensure_Modify_firmware_environment_values_is_set_to_Administrators.yml
#- import_tasks: Ensure_Perform_volume_maintenance_tasks_is_set_to_Administrators.yml
#- import_tasks: Ensure_Profile_single_process_is_set_to_Administrators.yml
#- import_tasks: Ensure_Profile_system_performance_is_set_to_Administrators_NT-SERVICE_WdiServiceHost.yml
#- import_tasks: Ensure_Replace_a_process_level_token_is_set_to_LOCAL-SERVICE_NETWORK-SERVICE.yml
#- import_tasks: Ensure_Restore_files_and_directories_is_set_to_Administrators.yml
#- import_tasks: Ensure_Shut_down_the_system_is_set_to_Administrators.yml
#- import_tasks: Ensure_Take_ownership_of_files_or_other_objects_is_set_to_Administrators.yml
#- import_tasks: Ensure_Accounts_Guest_account_status_is_set_to_Disabled.yml
#- import_tasks: Ensure_Accounts_Limit_local_account_use_of_blank_passwords_to_console_logon_only_is_set_to_Enabled.yml
#- import_tasks: Configure_Accounts_Rename_administrator_account.yml
#- import_tasks: Configure_Accounts_Rename_guest_account.yml
#- import_tasks: Ensure_Audit_Force_audit_policy_subcategory_settings_Windows_Vista_or_later_to_override_audit_policy_category_settings_is_set_to_Enabled.yml
#- import_tasks: Ensure_Audit_Shut_down_system_immediately_if_unable_to_log_security_audits_is_set_to_Disabled.yml
#- import_tasks: Ensure_Devices_Prevent_users_from_installing_printer_drivers_is_set_to_Enabled.yml
#- import_tasks: Ensure_Domain_member_Digitally_encrypt_or_sign_secure_channel_data_always_is_set_to_Enabled.yml
#- import_tasks: Ensure_Domain_member_Digitally_encrypt_secure_channel_data_when_possible_is_set_to_Enabled.yml
#- import_tasks: Ensure_Domain_member_Digitally_sign_secure_channel_data_when_possible_is_set_to_Enabled.yml
#- import_tasks: Ensure_Domain_member_Disable_machine_account_password_changes_is_set_to_Disabled.yml
#- import_tasks: Ensure_Domain_member_Maximum_machine_account_password_age_is_set_to_30_or_fewer_days_but_not_0.yml
#- import_tasks: Ensure_Domain_member_Require_strong_Windows_2000_or_later_session_key_is_set_to_Enabled.yml
#- import_tasks: Ensure_Interactive_logon_Do_not_require_CTRL+ALT+DEL_is_set_to_Disabled.yml
#- import_tasks: Ensure_Interactive_logon_Dont_display_last_signed-in_is_set_to_Enabled.yml
#- import_tasks: Ensure_Interactive_logon_Machine_inactivity_limit_is_set_to_1800_or_fewer_seconds_but_not_0.yml
#- import_tasks: Configure_Interactive_logon_Message_text_for_users_attempting_to_log_on.yml
#- import_tasks: Configure_Interactive_logon_Message_title_for_users_attempting_to_log_on.yml 
#- import_tasks: Ensure_Interactive_logon_Prompt_user_to_change_password_before_expiration_is_set_to_between_5_and_14_days.yml
#- import_tasks: Ensure_Interactive_logon_Require_Domain_Controller_Authentication_to_unlock_workstation_is_set_to_Enabled_MS_only.yml
# - import_tasks: Ensure_Interactive_logon_Smart_card_removal_behavior_is_set_to_Lock-Workstation_or_higher.yml
 - import_tasks: Ensure_Microsoft_network_client_Digitally_sign_communications_always_is_set_to_Enabled.yml 
